run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 1m
  tests: false

linters:
  enable:
  # Default
  - govet
  - errcheck
  - staticcheck
  - unused
  - gosimple
  - structcheck
  - varcheck
  - ineffassign
  - deadcode
  - typecheck
  # Extra, see list of https://golangci-lint.run/usage/linters/
  - bodyclose
  - unconvert
  - dupl
  - goconst
  - gocyclo
  - asciicheck
  - gofmt
  - goimports
  - misspell
  - dogsled
  - nakedret
  - prealloc
  - gocritic
  - goprintffuncname
  - exhaustive
  - nolintlint
