version: 2

# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
defaults: &defaults
  docker:
    - image: docker.io/weaveworks/wksctl-build:go-1.14.1-431fabe9
      environment:
        GOPATH: /go/
        SRCDIR: /src/github.com/weaveworks/wksctl
        KUBECTL_URL: https://dl.k8s.io/v1.18.3/kubernetes-client-linux-amd64.tar.gz
        KUBECTL_CHECKSUM: 2096615904534a381d02ec15d62fe4e7fb80ef0d8e5fcfee2e71ba94771adfab
  working_directory: /src/github.com/weaveworks/cluster-api-provider-existinginfra

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - unit-tests
      - integration-tests
      - release:
          requires:
            - build
            - unit-tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: make
      - run:
          name: Check that generated files have not been changed since checkout
          command: |
            echo "The following files have been modified since checkout or are unknown to Git:"
            ! (git status --porcelain | grep -E '^( M)|(??)')
      - run:
          # Allow builds from forks
          name: Push image if docker login is available
          command: |
            if [ -n "$DOCKER_IO_PASSWORD" ]; then
              docker login -u "$DOCKER_IO_USER" -p "$DOCKER_IO_PASSWORD" docker.io
              make push
            fi
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -L $KUBECTL_URL -o kubectl.tar.gz
            echo "$KUBECTL_CHECKSUM kubectl.tar.gz" | sha256sum -c
            tar xvzf kubectl.tar.gz --strip-components=3
            sudo mv kubectl /usr/local/bin

      - run:
          name: Run unit tests
          command: |
            go version
            make test
  integration-tests:
    <<: *defaults
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -L $KUBECTL_URL -o kubectl.tar.gz
            echo "$KUBECTL_CHECKSUM kubectl.tar.gz" | sha256sum -c
            tar xvzf kubectl.tar.gz --strip-components=3
            sudo mv kubectl /usr/local/bin

      - run:
          name: Run integration tests
          command: |
            go version
            cd test/integration/test
            go test --timeout=99999s
  release:
    <<: *defaults
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | IMAGE_TAG=`tools/image-tag` bash
